In [1]:
import model, BeamFeatures
import torch
import matplotlib.pyplot as plt, numpy as np
# m = model.GNNModel(outdim=4)
# checkpoint = torch.load('test.cpt')
# m.load_state_dict(checkpoint['model_state_dict'])
bf = BeamFeatures.BeamFeatures('/home/jake/GNN_work/data/1_9_23_pdgs/merged_train.h5', style='pdgs', ave_charge=True)

In [2]:
data = bf[0]

In [13]:
data

Data(x=[338, 4], edge_index=[2, 1690], edge_attr=[1690, 8], y=[1, 4], index=0)

In [12]:
print(data.edge_attr[:3])
print(data.edge_index[:,:3])

tensor([[-4.2230e-01, -4.7999e+00,  0.0000e+00, -6.7656e+02,  5.8544e+02,
          5.7631e+01, -3.3381e+00,  2.0139e+01],
        [-3.0005e-01, -5.5999e+00,  0.0000e+00, -6.7662e+02,  5.8584e+02,
          5.7631e+01, -2.2978e+00,  1.9619e+01],
        [-3.4027e-01,  3.2799e+02,  0.0000e+00, -6.7660e+02,  4.1905e+02,
          5.7631e+01, -5.0378e+00,  2.0989e+01]])
tensor([[0, 0, 0],
        [1, 2, 3]])


In [5]:
# import h5py as h5
# f = h5.File('/home/jake/GNN_work/data/1_9_23_pdgs/merged.h5', 'r')

In [6]:
# f['edge_features'][0]

array([ 2.1029968e+01, -1.3399644e+02, -4.1689224e+01,  2.5555447e+01,
        0.0000000e+00,  0.0000000e+00,  5.7485104e-02,  0.0000000e+00,
        0.0000000e+00,  4.0002701e+01,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  1.0000000e+00], dtype=float32)