In [1]:
import NuFeatures
import model
import torch

In [2]:
nf = NuFeatures.NuFeatures('try_nu.h5')

In [4]:
m = model.NuModel()

In [5]:
from torch_geometric.loader import DataLoader
loader = DataLoader(nf,
                    shuffle     = False,
                    num_workers = 0,
                    batch_size  = 10
                    )

In [6]:
data = next(iter(loader))

In [17]:
nout = sum(m.branches.values())

In [18]:
data.y.reshape((-1,nout))[:,0]

tensor([0., 0., 0., 0., 0.])

In [19]:
data.y.reshape((-1,nout))[:,1:5].argmax(axis=1)

tensor([1, 3, 3, 1, 1])

In [20]:
data.y.reshape((-1,nout))[:,5:9].argmax(axis=1)

tensor([2, 2, 2, 2, 3])

In [23]:
data.y.reshape((-1,nout))[:,9:13].argmax(axis=1)

tensor([0, 0, 0, 0, 0])

In [24]:
data.y.reshape((-1,nout))[:,13:17].argmax(axis=1)

tensor([0, 0, 0, 0, 0])

In [25]:
data.y.reshape((-1,nout))[:,17:21].argmax(axis=1)

tensor([0, 0, 0, 0, 0])

In [26]:
data.y.reshape((-1,nout))[:,21:].argmax(axis=1)

tensor([1, 1, 1, 1, 0])

In [27]:
x = m(data, data.batch)

In [34]:
x

{'sign': tensor([[0.5061],
         [0.5487],
         [0.4749],
         [0.3616],
         [0.5688]], grad_fn=<SigmoidBackward0>),
 'flavor': tensor([[0.1861, 0.3434, 0.2469, 0.2235],
         [0.2181, 0.3033, 0.2366, 0.2420],
         [0.3318, 0.2033, 0.2746, 0.1903],
         [0.3512, 0.1587, 0.1930, 0.2972],
         [0.2189, 0.2360, 0.2518, 0.2933]], grad_fn=<SoftmaxBackward0>),
 'mode': tensor([[0.2413, 0.1986, 0.3294, 0.2307],
         [0.2075, 0.2065, 0.2109, 0.3751],
         [0.3507, 0.2148, 0.2057, 0.2288],
         [0.2836, 0.2523, 0.2709, 0.1931],
         [0.2116, 0.3172, 0.2672, 0.2039]], grad_fn=<SoftmaxBackward0>),
 'protons': tensor([[0.1471, 0.1441, 0.3513, 0.3575],
         [0.2683, 0.3292, 0.1806, 0.2219],
         [0.2811, 0.3224, 0.2370, 0.1595],
         [0.1604, 0.1737, 0.3428, 0.3231],
         [0.2530, 0.2534, 0.1396, 0.3540]], grad_fn=<SoftmaxBackward0>),
 'pions': tensor([[0.2265, 0.2199, 0.1654, 0.3881],
         [0.2304, 0.3180, 0.2623, 0.1893],
        

In [33]:
torch.round(x['sign'])

tensor([[1.],
        [1.],
        [0.],
        [0.],
        [1.]], grad_fn=<RoundBackward0>)

In [35]:
vals = {n:v.argmax(axis=1) for n,v in x.items()}

In [36]:
vals

{'sign': tensor([0, 0, 0, 0, 0]),
 'flavor': tensor([1, 1, 0, 0, 3]),
 'mode': tensor([2, 3, 0, 0, 1]),
 'protons': tensor([3, 1, 1, 2, 3]),
 'pions': tensor([3, 1, 1, 1, 2]),
 'pi0s': tensor([0, 2, 0, 1, 1]),
 'neutrons': tensor([2, 2, 1, 3, 0])}