In [1]:
import model, BeamFeatures

In [2]:
import matplotlib.pyplot as plt, numpy as np

In [3]:
m = model.GNNModel()

In [13]:
bf = BeamFeatures.BeamFeatures('/home/jake/GNN_work/data/merged.h5', norm_path='norms.h5')

In [5]:
bf[0].y

tensor([[1., 0., 0., 0., 0., 0.]])

In [14]:
bf[0].edge_attr

tensor([[  0.8482,  -2.0688,  -4.6048,  ...,  -0.4882,   0.4028,  -0.4736],
        [  4.0068,   3.1005, -10.5105,  ...,  -0.4882,   0.3478,  -0.4736],
        [  4.3069,  -6.6071, -10.4084,  ...,   0.0259,   0.0198,  -0.4736],
        ...,
        [ -0.0524,  -0.0251,   0.1465,  ...,   2.2830,   2.1579,   3.1143],
        [ -0.2595,   0.0951,   0.5196,  ...,   1.8302,   1.8868,   2.7996],
        [ -0.3235,   0.1251,   0.6216,  ...,   1.9141,   1.8936,   2.8088]],
       dtype=torch.float64)

In [7]:
from torch_geometric.loader import DataLoader
loader = DataLoader(bf,
                    shuffle     = True,
                    num_workers = 0,
                    batch_size  = 10
                    )

In [8]:
bf[0].x[:,0].detach().numpy()

array([-6.93579388e+00, -7.07751036e+00, -7.66736889e+00, -7.86778212e+00,
       -7.61617851e+00, -3.78236234e-01, -3.76969039e-01,  4.30984646e-01,
        4.31880087e-01,  4.30968285e-01,  4.30771738e-01,  4.32398707e-01,
        4.31877047e-01,  4.32266474e-01,  4.30329949e-01,  4.30821031e-01,
        4.30913001e-01,  4.30573344e-01,  4.29457724e-01,  4.29599822e-01,
        4.26941574e-01,  4.27132607e-01,  4.27299112e-01,  4.25815016e-01,
        4.25573021e-01,  4.25744712e-01,  4.23166215e-01,  4.23202217e-01,
        4.23439592e-01,  4.21915352e-01,  4.21881437e-01,  4.21700686e-01,
        4.19261724e-01,  4.19568688e-01,  4.17606503e-01,  4.17881638e-01,
        4.14650828e-01,  4.14632112e-01,  4.13859129e-01,  4.13949192e-01,
        4.13982660e-01,  4.11827207e-01,  4.11892951e-01,  4.12060469e-01,
        4.10683990e-01,  4.10609901e-01,  4.10502583e-01,  4.08419281e-01,
        4.08611149e-01,  4.08627957e-01,  4.07153159e-01,  4.07024145e-01,
        4.07046646e-01,  

In [9]:
for i in bf:
    xs += i.x[:,0].detach().numpy()

NameError: name 'xs' is not defined

In [ ]:
bf[0].edge_attr.shape

In [ ]:
plt.hist(bf[0].edge_attr[:,2].detach().numpy())

In [ ]:
data = next(iter(loader))

In [ ]:
m(data,  data.batch) ##ADD SIGMOID AT OUTPUT

In [ ]:
data

In [ ]:
def plot_scatter3d(voxels, labels={}, edge_index=None, clust_labels=None, markersize=5, colorscale=None):
    
    import copy
    import plotly.graph_objects as go # Plotly graph objects
    from plotly.offline import iplot  # Interactive plots
    import plotly.express as px # For discrete color scale
    
    if colorscale is None:
        colorscale = px.colors.qualitative.Dark24

    # Initialize a graph with no labels
    blank = go.Scatter3d(x = voxels[:,0],
                         y = voxels[:,1],
                         z = voxels[:,2],
                         mode = 'markers', 
                         marker = dict(
                             size = 2, 
                             colorscale = colorscale
                         )
                        )
    
    # Loop over the set of labels, make a graph for each
    #graphs = []
    graphs = [blank]
#     for key, label in labels.items():
#         graph = copy.copy(blank)
#         graph['name'] = key
#         graph['marker']['color'] = label
#         graph['hovertext'] = [f'{l:0.0f}' for l in label]
#         graphs.append(graph)
        
#     if not len(graphs):
#         graphs.append(blank)
        
    # Draw edges if requested
#     if edge_index is not None:
#         import scipy as sp
#         edge_vertices = []
#         clust_labels = np.unique(clust_labels, return_inverse=True)[1]
#         for i, j in edge_index:
#             vi, vj = voxels[clust_labels==i], voxels[clust_labels==j]
#             d12 = sp.spatial.distance.cdist(vi, vj, 'euclidean')
#             i1, i2 = np.unravel_index(np.argmin(d12), d12.shape)
#             edge_vertices.append([vi[i1], vj[i2], [None, None, None]])

#         edge_vertices = np.concatenate(edge_vertices)

#         graphs.append(go.Scatter3d(x = edge_vertices[:,0], y = edge_vertices[:,1], z = edge_vertices[:,2],
#                                    mode = 'lines',
#                                    name = 'Predicted edges',
#                                    line = dict(
#                                         width = 2,
#                                         color = 'Blue'
#                                     ),
#                                     hoverinfo = 'none'))

    iplot(graphs)

In [ ]:
data.x[0,:3].shape

In [ ]:
plot_scatter3d(data.x[data.batch == 0,:3].reshape(-1,3))

In [ ]:
import h5py as h5
import numpy as np

In [ ]:
f = h5.File('test.h5', 'w')

In [ ]:
f.create_dataset('asdf', (2,), dtype=h5.vlen_dtype(np.dtype('float32')), maxshape=(None,))

In [ ]:
d = f['asdf']

In [ ]:
d.resize(3, axis=0)

In [ ]:
d

In [ ]:
f.close()

In [ ]:
pred = m(data,  data.batch)

In [ ]:
pred

In [ ]:
plt.hist(pred.flatten().detach().numpy())

In [ ]:
pred.argmax(axis=1)

In [ ]:
(data.y.argmax(axis=1) == pred.argmax(axis=1)).sum()

In [ ]:
data.y[pred.argmax(axis=1)]